spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8080
